import json
from pathlib import Path
p=Path('src/banks.json'); d=json.loads(p.read_text())
extra={
'pboc':('🇨🇳','Hold · targeted easing bias',-1,"People's Bank of China / State Council",'Liquidity operations, bank funding, LPRs and the renminbi.','Credit demand, property support, LPR fixings and reserve-ratio signals.','Traditionally growth-sensitive and state-coordinated; the present signal is a dovish tilt through liquidity support rather than a broad rate cut.','Benchmarks were held while liquidity support remained active. That mix reads as cautiously accommodative.','Governor since 2023','A veteran central banker and foreign-exchange regulator, Pan previously led SAFE and served as a PBOC deputy governor.','PBOC leadership profile'),
'rbi':('🇮🇳','Hold · neutral stance',0,'Reserve Bank of India','Repo-linked money-market rates, bank funding and loan benchmarks.','Food inflation, core inflation, growth momentum and liquidity conditions.','The MPC is data-dependent rather than structurally hawkish or dovish; its latest neutral stance balances inflation with growth.','An unchanged repo rate and neutral language imply no strong directional bias.','Governor since December 2024','Sanjay Malhotra is a career civil servant who previously served as India’s Revenue Secretary and held senior finance and power-sector roles.','RBI appointment release'),
'mas':('🇸🇬','Tighten · slightly steeper slope',1,'Monetary Authority of Singapore','A managed trade-weighted exchange rate changes imported inflation and competitiveness.','Core inflation, imported costs, growth and the S$NEER band’s slope.','MAS is pragmatic and forecast-led. The latest calibrated steepening gives the team a hawkish tilt without using an interest-rate target.','A slightly faster appreciation path is a measured tightening signal.','Managing Director since January 2024','Chia Der Jiun previously served as Permanent Secretary at Singapore’s Ministry of Manpower and held senior roles at MAS, the Ministry of Finance and the Public Service Division.','Singapore Government Directory'),
'boe':('🇬🇧','Hold · 6–3, three sought hike',1,'Bank of England','Bank Rate and expectations feed into sterling, gilt yields, deposits and mortgages.','Energy prices, wage setting, services inflation and second-round effects.','The MPC is divided: the majority held, while three members preferred a hike. The collective signal is a hawkish tilt.','Holding amid three votes for a rise and stronger inflation warnings is hawkish relative to a simple hold.','Governor since March 2020','Andrew Bailey previously led the UK Financial Conduct Authority and served as the Bank’s Deputy Governor for prudential regulation and chief cashier.','Bank of England biography'),
'ecb':('🇪🇺','Raise · +25 bp',2,'European Central Bank','Policy rates move euro money markets, bank funding, sovereign yields and the euro.','Wage growth, services inflation, energy prices and differences in transmission across member states.','The Governing Council’s latest rate increase and inflation language make the current team signal hawkish, though decisions remain meeting-by-meeting.','A 25 bp increase is an unambiguous tightening action.','President since November 2019','Christine Lagarde previously led the IMF and served as France’s finance minister; she is a lawyer by training rather than a career monetary economist.','ECB executive biography'),
'fed':('🇺🇸','Raise · +25 bp, unanimous',2,'Federal Reserve Board','Fed funds expectations move the dollar, Treasury yields, credit spreads and bank prime rates globally.','Core inflation, payrolls, unemployment, demand resilience and inflation expectations.','The 2026 FOMC includes varied regional and Board views, but its unanimous September hike makes the current collective signal hawkish.','A unanimous increase to support a faster return to 2% inflation is clearly hawkish.','Chairman in 2026','Kevin Warsh previously served as a Federal Reserve governor and worked in investment banking and economic policy. His official testimony stresses price stability and policy credibility.','Federal Reserve biography'),
'boc':('🇨🇦','Hold · balanced risk assessment',0,'Bank of Canada','The overnight target influences Canadian money markets, bank prime rates, mortgages and the Canadian dollar.','Underlying inflation, household demand, trade uncertainty and labor-market slack.','The Governing Council balances inflation risk against economic weakness. The latest hold reads as balanced rather than strongly hawkish or dovish.','A hold with two-sided risks gives little directional conviction.','Governor since June 2020','Tiff Macklem previously served as the Bank’s senior deputy governor and as dean of the Rotman School of Management; he also worked at Canada’s Department of Finance.','Bank of Canada profile')}
for b in d:
    icon,decision,score,source,transmission,watch,team,note,tenure,bg,biosource=extra[b['id']]
    b.update(icon=icon,decision=decision,stanceScore=score,sourceName=source,transmission=transmission,watch=watch,teamRead=team,stanceNote=note)
    b['leader'].update(tenure=tenure,background=bg,sourceName=biosource)
    for n in b.get('news',[]): n.setdefault('sourceName',source)
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
