const SOURCES={boe:'https://www.bankofengland.co.uk/monetary-policy/the-interest-rate-bank-rate',ecb:'https://www.ecb.europa.eu/home/html/index.en.html',rbi:'https://www.rbi.org.in/',boc:'https://www.bankofcanada.ca/valet/observations/V39079,V80691311/json?recent=1',fed:'https://www.federalreserve.gov/monetarypolicy/openmarket.htm',pboc:'https://www.pbc.gov.cn/en/3688229/3688338/3688341/index.html',mas:'https://www.mas.gov.sg/monetary-policy'};
const FEEDS={fed:'https://www.federalreserve.gov/feeds/press_monetary.xml',ecb:'https://www.ecb.europa.eu/rss/press.html'};
const clean=s=>s.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&(?:nbsp|#160);/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
async function get(url){const r=await fetch(url,{headers:{'User-Agent':'CentralBankWatch/1.0 (educational dashboard)','Accept':'text/html,application/json,application/xml,text/xml'},signal:AbortSignal.timeout(14000)});if(!r.ok)throw Error('Source unavailable');return r.text();}
const num=s=>{const n=Number(s);if(!Number.isFinite(n)||n<0||n>30)throw Error('Invalid rate');return n.toFixed(2)+'%';};
function parseRates(id,raw,at){const text=clean(raw),date='Current source · checked '+at.slice(0,10),base={};if(id==='boc'){const d=JSON.parse(raw);for(const o of d.observations||[]){if(o.V39079){base.rate=num(o.V39079.v);base.rateDate=o.d+' observation';}if(o.V80691311){base.prime=num(o.V80691311.v);base.primeDate=o.d+' observation';base.primeSource=SOURCES.boc;}}}
if(id==='boe'){const m=text.match(/Current Bank Rate\s+([\d.]+)\s*%/);if(m){base.rate=num(m[1]);base.rateDate=date;}}
if(id==='ecb'){const m=text.match(/Deposit facility\s+([\d.]+)\s*%/);if(m){base.rate=num(m[1]);base.rateDate=date;}}
if(id==='rbi'){const m=text.match(/Policy\s+Repo\s+Rate\s*:?\s*([\d.]+)\s*%/);if(m){base.rate=num(m[1]);base.rateDate=date;}}
if(id==='fed'){const rows=[...raw.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(x=>clean(x[1]));const row=rows.find(x=>/\b\d{1,2}\.\d{2}\s*[-–]\s*\d{1,2}\.\d{2}\b/.test(x));const m=row?.match(/(\d{1,2}\.\d{2})\s*[-–]\s*(\d{1,2}\.\d{2})/);if(m&&Number(m[1])<=Number(m[2])&&Number(m[2])-Number(m[1])<=1){base.rate=num(m[1]).slice(0,-1)+'–'+num(m[2]);base.rateDate=date;}}
if(base.rate)base.rateSource=SOURCES[id];return base;}
function parseFeed(raw,url){const host=new URL(url).hostname;return [...raw.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)].map(x=>{const v=t=>clean(x[1].match(new RegExp('<'+t+'[^>]*>([\\s\\S]*?)</'+t+'>','i'))?.[1]||'');return {title:v('title'),url:v('link'),date:v('pubDate')||v('dc:date')};}).filter(x=>{try{return x.title&&new URL(x.url).hostname===host&&Date.parse(x.date)<=Date.now();}catch{return false;}}).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date)).slice(0,3);}
async function check(id,at){const b={id,message:'Automatic check unavailable · last verified value retained.'};const jobs=[(async()=>{try{const raw=await get(SOURCES[id]);const v=parseRates(id,raw,at);Object.assign(b,v);b.message=v.rate?'Official rate source checked; observation date shown above.':'Source reached; automatic rate extraction unavailable. Dated research retained.';}catch{}})()];if(FEEDS[id])jobs.push((async()=>{try{b.news=parseFeed(await get(FEEDS[id]),FEEDS[id]);}catch{}})());await Promise.all(jobs);return b;}
let memo=null,pending=null;
async function refreshData(){if(memo&&Date.now()-Date.parse(memo.checkedAt)<300000)return memo;if(pending)return pending;pending=(async()=>{const checkedAt=new Date().toISOString();const banks=await Promise.all(Object.keys(SOURCES).map(id=>check(id,checkedAt)));memo={checkedAt,banks};return memo;})();try{return await pending;}finally{pending=null;}}
export default {async fetch(request){const u=new URL(request.url);if(u.pathname==='/api/refresh'){if(request.method!=='GET')return new Response('Method not allowed',{status:405});try{return Response.json(await refreshData(),{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Sources unavailable'},{status:502});}}if(u.pathname==='/'||u.pathname==='/index.html')return new Response(HTML,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'}});return new Response('Not found',{status:404});}};
export {parseRates,parseFeed};
